DjangoOscar/mysite/mysite/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static
from bootstrap_test import views
from django.contrib.auth.views import LogoutView
from bootstrap_test import views as user_views  # Замените на ваше приложение
#from .views import edit_file, delete_file
from bootstrap_test.views import edit_file, delete_file  # Импорт функций



urlpatterns = [
    path("", views.home, name="home"),  # Путь для главной страницы
    path("admin/", admin.site.urls),
    path("about/", views.about, name="about"),
    path("gallery/", views.gallery, name="gallery"),
    path("pricing/", views.pricing, name="pricing"),
    path("contact/", views.contact, name="contact"),
    path('upload/', views.upload_file, name='upload'),
    path("get_schemas/", views.get_schemas, name="get_schemas"),
    path("redact_form/", views.redact_form, name="redact_form"),
    path("login/", views.login_view, name="login"),

    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path('register/', user_views.register, name='register'),
    path('user_profile/', views.user_profile_view, name='user_profile'),

    path("profile/", views.profile, name="profile"),
    path('user_statistic/', views.user_statistic, name='user_statistic'),  # Проверьте правильность пути
    path('user_uploads/', views.user_uploads, name='user_uploads'),   # Добавляем путь для user_uploads

    path('edit_file/<int:file_id>/', edit_file, name='edit_file'),
    path('delete_file/<int:file_id>/', delete_file, name='delete_file'),



]

# Добавляем обработчик для медиа-файлов только в режиме отладки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoOscar/mysite/mysite/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator



class AI_Models(models.Model):
    
    name = models.CharField("Название", max_length=1000, null=True, blank=True)
    short_name = models.CharField("Короткое название", max_length=100, null=True, blank=True)
    mission = models.CharField("Назначение", max_length=1000, null=True, blank=True)
    link_github = models.CharField("Ссылка на github", max_length=1000, null=True, blank=True)
    ai_model = models.FileField("Ссылка для загрузки", upload_to='ai_model/', null=True, blank=True)
    version = models.CharField("Версия XML", max_length=20, null=True, blank=True)
    date_public = models.DateField("Дата публикации", default=datetime.date.today)
    date_upload = models.DateField("Дата загрузки на сайт", default=datetime.date.today)
    date_unused = models.DateField("Дата прекращения использования", default=datetime.date.today)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Нейросеть для преобразования"  
        verbose_name_plural = "Нейросети для преобразования"

    # Добавьте другие поля, если необходимо

    def __str__(self):
        return self.name


class XMLSchema(models.Model):
    STAGE_CHOICES = (
        ('building', 'Этап проектирования'),
        ('exploitation', 'Этап строительства'),
    )

    name = models.CharField("Название", max_length=1000, null=True, blank=True)
    short_name = models.CharField("Короткое название", max_length=100, null=True, blank=True)
    stage = models.CharField("Этап", max_length=20, choices=STAGE_CHOICES, null=True)
    file_schem_xsl = models.FileField("Файл XML схемы (XSL)", upload_to='xml_schemas/', null=True, blank=True)
    file_schem_xsd = models.FileField("Файл XML схемы (XSD)", upload_to='xml_schemas/', null=True, blank=True)
    file_annot = models.FileField("Файл аннотации (PDF)", upload_to='xml_schemas/', null=True, blank=True)
    date_public = models.DateField("Дата публикации", default=datetime.date.today)
    date_upload = models.DateField("Дата загрузки на сайт", default=datetime.date.today)
    date_unused = models.DateField("Дата прекращения использования", default=datetime.date.today)
    version = models.CharField("Версия XML", max_length=20, null=True, blank=True)
    normative = models.CharField("Норматив", max_length=1000, null=True, blank=True)
    link = models.CharField("Ссылка", max_length=1000, null=True, blank=True)
    ai_model = models.ForeignKey('AI_Models', verbose_name="Модель для преобразования", null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "XML схема"  
        verbose_name_plural = "XML схемы"  
    
    @classmethod
    def get_schema_choices(cls):
        # Возвращаем выборку схем
        return cls.objects.values_list('id', 'name')


class UploadedFile(models.Model):
#    file = models.FileField(upload_to='uploads/')
    file = models.FileField(upload_to='uploads/', validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    name = models.CharField(max_length=255)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.file.name
    

    
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField("Имя", max_length=30, null=True, blank=True)
    surname = models.CharField("Фамилия", max_length=30, null=True, blank=True)
    last_name = models.CharField("Отчество", max_length=30, null=True, blank=True)
    photo = models.ImageField("Фото", upload_to='uploads/uploads_bio/', null=True, blank=True)
    company = models.CharField("Организация", max_length=255, null=True, blank=True)
    date_birth = models.DateField("Дата рождения", null=True, blank=True)
    date_joined = models.DateTimeField("Дата регистрации", default=datetime.date.today)
    groups = models.CharField("Группы", max_length=255, null=True, blank=True)
    
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Профиль пользователя"
        verbose_name_plural = "Профили пользователей"

DjangoOscar/mysite/mysite/forms.py
#forms.py
from multiupload.fields import MultiFileField
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import UploadedFile
from mysite.models import UploadedFile
from django.core.validators import FileExtensionValidator



class FileUploadForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['file']  # Поля формы, которые необходимо включить
        validators=[FileExtensionValidator(allowed_extensions=['pdf'])]


class AnalysisResultsForm(forms.Form):
    results = forms.CharField(widget=forms.Textarea)


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class FileEditForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['name']

DjangoOscar/mysite/templates/profile/admin_ai_models.html
<!-- profile/admin_ai_models.html -->

{% block content %}
<div class="container mt-5">
    <h3>Все нейросети и XML-схемы</h3>

    <p>
        <h4>XML схемы</h4>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Название</th>
                    <th>Короткое название</th>
                    <th>Этап</th>
                    <th>Файл схемы (XSL)</th>
                    <th>Файл схемы (XSD)</th>
                    <th>Файл аннотации (PDF)</th>
                    <th>Дата публикации</th>
                    <th>Дата загрузки</th>
                    <th>Дата прекращения использования</th>
                    <th>Версия XML</th>
                    <th>Норматив</th>
                    <th>Ссылка</th>
                    <th>Модель для преобразования</th>
                </tr>
            </thead>
            <tbody>
                {% for schema in schemas %}
                <tr>
                    <td>{{ schema.id }}</td>
                    <td>{{ schema.name }}</td>
                    <td>{{ schema.short_name }}</td>
                    <td>{{ schema.get_stage_display }}</td>
                    <td>
                        {% if schema.file_schem_xsl %}
                            <a href="{{ schema.file_schem_xsl.url }}">Скачать</a>
                        {% else %}
                            Нет файла
                        {% endif %}
                    </td>
                    <td>
                        {% if schema.file_schem_xsd %}
                            <a href="{{ schema.file_schem_xsd.url }}">Скачать</a>
                        {% else %}
                            Нет файла
                        {% endif %}
                    </td>
                    <td>
                        {% if schema.file_annot %}
                            <a href="{{ schema.file_annot.url }}">Скачать</a>
                        {% else %}
                            Нет файла
                        {% endif %}
                    </td>
                    <td>{{ schema.date_public }}</td>
                    <td>{{ schema.date_upload }}</td>
                    <td>{{ schema.date_unused }}</td>
                    <td>{{ schema.version }}</td>
                    <td>{{ schema.normative }}</td>
                    <td>{{ schema.link }}</td>
                    <td>{{ schema.ai_model }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="14">No XML / models uploaded yet</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <p>
    <h4>Нейросети</h4>
    *** Таблица с нейросетями ***
</div>
{% endblock %}

DjangoOscar/mysite/templates/profile/admin_full_statistic.html
<!-- profile/admin_full_statistic.html -->

{% block content %}

<h3>Вся статистика</h3>

{% endblock %}

DjangoOscar/mysite/templates/profile/admin_partners.html
<!-- profile/admin_partners.html -->

{% block content %}

<h3>Партнерские программы</h3>

{% endblock %}

DjangoOscar/mysite/templates/profile/admin_projects.html
<!-- profile/admin_projects.html -->

{% block content %}

<h3>Все проекты</h3>

{% endblock %}

DjangoOscar/mysite/templates/profile/admin_subscribe.html
<!-- profile/admin_subscribe.html -->

{% block content %}

<h3>Правила подписки</h3>

{% endblock %}

DjangoOscar/mysite/templates/profile/admin_users.html
<!-- profile/admin_users.html -->


{% block content %}
<div class="container mt-5">
    <h3>Все пользователи</h3>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Логин</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Отчество</th>
                    <th>Фото</th>
                    <th>Организация</th>
                    <th>Электронная почта</th>
                    <th>Дата регистрации</th>
                    <th>Дата рождения</th>
                    <th>Добавлен в группы</th>
                    <th>Статус Администратора</th>
                    <th>Статус Персонала</th>
                    <th>Активность</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.surname }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.photo }}</td>
                    <td>{{ user.company }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.date_joined }}</td>
                    <td>{{ user.date_birth }}</td>
                    <td>{{ user.groups }}</td>
                    <td>{{ user.is_superuser|yesno:"Да,Нет" }}</td>
                    <td>{{ user.is_staff|yesno:"Да,Нет" }}</td>
                    <td>{{ user.is_active|yesno:"Да,Нет" }}</td>

                </tr>
                {% empty %}
                    <tr>
                        <td colspan="14">No users registred yet</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

DjangoOscar/mysite/templates/profile/user_prof.html
{% block content %}


<div class="container-fluid mt-4">
    <div class="col-md-9">
        <div class="profile-pic">
            {% if user.userprofile.photo %}
                <img src="{{ user.userprofile.photo.url }}" alt="Фото" class="img-thumbnail">
            {% else %}
                <img src="uploads_bio/default_bio.jpg" alt="Фото" class="img-thumbnail">
                Нет фото
            {% endif %}
        </div>
        <form method="POST" action="{% url 'profile' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">Логин</label>
                <input type="text" class="form-control" id="id_username" name="username" value="{{ user.username }}" readonly>
            </div>
            <div class="form-group">
                <label for="id_first_name">Имя</label>
                <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ user.first_name }}">
            </div>
            <div class="form-group">
                <label for="id_surname">Фамилия</label>
                <input type="text" class="form-control" id="id_surname" name="surname" value="{{ user.userprofile.surname }}">
            </div>
            <div class="form-group">
                <label for="id_last_name">Отчество</label>
                <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ user.userprofile.last_name }}">
            </div>
            <div class="form-group">
                <label for="id_email">Почта</label>
                <input type="email" class="form-control" id="id_email" name="email" value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label for="id_company">Организация</label>
                <input type="text" class="form-control" id="id_company" name="company" value="{{ user.userprofile.company }}">
            </div>
            <div class="form-group">
                <label for="id_date_birth">Дата рождения</label>
                <input type="date" class="form-control" id="id_date_birth" name="date_birth" value="{{ user.userprofile.date_birth }}">
            </div>
            <div class="form-group">
                <label for="id_date_joined">Дата регистрации</label>
                <input type="text" class="form-control" id="id_date_joined" name="date_joined" value="{{ user.date_joined }}" readonly>
            </div>
            <div class="form-group">
                <label for="id_is_superuser">Статус администратора</label>
                <input type="text" class="form-control" id="id_is_superuser" name="is_superuser" value="{{ user.is_superuser|yesno:"Да,Нет" }}" readonly>
            </div>
            <button type="submit" class="btn btn-success">Сохранить изменения</button>
        </form>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const userTabs = document.querySelectorAll("#v-pills-tab .nav-link");
        const adminTabs = document.querySelectorAll("#adminTab .nav-link");

        userTabs.forEach(tab => {
            tab.addEventListener("click", () => {
                adminTabs.forEach(adminTab => adminTab.classList.remove("active"));
            });
        });

        adminTabs.forEach(tab => {
            tab.addEventListener("click", () => {
                userTabs.forEach(userTab => userTab.classList.remove("active"));
            });
        });
    });
</script>


{% endblock %}

DjangoOscar/mysite/templates/profile/user_settings.html
<!-- profile/user_settings.html -->

{% block content %}

<h3>Настройки</h3>

{% endblock %}

DjangoOscar/mysite/templates/profile/user_statistic.html
<!-- profile/user_statistic.html -->


{% block content %}
<h3>Статистика</h3>

<p>Всего файлов загружено: {{ total_files }}</p>
<p>Пользователь: {{ user.username }}</p>



{% endblock %}

DjangoOscar/mysite/templates/profile/user_uploads.html
<!-- profile/user_uploads.html -->

{% block content %}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="users" role="tabpanel" aria-labelledby="users-tab">
            <table class="table table-bordered table-striped">
                <thead class="table-info">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Login</th>
                        <th scope="col">Документ</th>
                        <th scope="col">Дата добавления</th>
                        <th scope="col">XML схема</th>
                        <th scope="col">статус XML разметки</th>
                        <th scope="col">Редактирование</th>
                    </tr>
                </thead>
                <tbody>
                    {% for file in uploaded_files %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ user.username }}</td>
                        <td>{{ file.name }}</td>
                        <td>{{ file.uploaded_at }}</td>
                        <td>{{ file.xml }}</td>
                        <td>{{ file.xml_status }}</td>
                        <td>
                            <a href="{% url 'edit_file' file.id %}" class="btn btn-primary btn-sm">Редактировать</a>
                            <button class="btn btn-danger btn-sm delete-file-btn" data-file-id="{{ file.id }}">Удалить</button>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7">No files uploaded yet</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>




<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.delete-file-btn').forEach(function(button) {
        button.addEventListener('click', function() {
            const fileId = this.getAttribute('data-file-id');
            const csrfToken = '{{ csrf_token }}'; // Получение CSRF токена

            if (confirm('Вы уверены, что хотите удалить этот файл?')) {
                fetch(`/delete_file/${fileId}/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': csrfToken,  // Добавление CSRF токена в заголовок
                        'Content-Type': 'application/json'
                    },
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        document.getElementById(`file-${fileId}`).remove();
                    } else {
                        alert('Ошибка при удалении файла');
                    }
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('Ошибка при удалении файла');
                });
            }
        });
    });
});
</script>

{% endblock %}

DjangoOscar/mysite/templates/profile/users_tab.html
<table class="table table-bordered mt-3">
    <thead>
        <tr>
            <th>Колонка 1</th>
            <th>Колонка 2</th>
            <th>Колонка 3</th>
            <th>Колонка 4</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>{{ user.field1 }}</td>
            <td>{{ user.field2 }}</td>
            <td>{{ user.field3 }}</td>
            <td>{{ user.field4 }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>